#!/usr/bin/env bash
# Host-native headless GSD runner. Claude uses a trimmed MCP config because a
# full user MCP config overflows 200k context (spike-proven); Codex invokes the
# GSD skill installed for Codex and stays on Codex models.
# Usage: gsd-run.sh <slash-command> [args...]
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$SCRIPT_DIR/adversary-host.sh"
. "$SCRIPT_DIR/model-equivalents.sh"

if [ $# -lt 1 ]; then
  echo "usage: gsd-run.sh <slash-command> [args...]" >&2
  exit 2
fi

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$REPO_ROOT" || exit 1

# gsd's mempalace commands call a bare `mempalace` binary in headless mode —
# resolve to the repo's gbrain-backed shim (spec 002 Phase D).
export PATH="$REPO_ROOT/scripts/gsd:$PATH"

TIMEOUT_SECS="${TIMEOUT:-900}"
LOG_DIR="$REPO_ROOT/.planning/logs"
mkdir -p "$LOG_DIR"
TS="$(date +%Y%m%d-%H%M%S)"
LOG_FILE="$LOG_DIR/gsd-run-${TS}.log"

ACTIVE_HOST="$(detect_orchestrator_host)" || exit $?
LEAD_TIER="${GSD_LEAD_MODEL:-sonnet}"
COMMAND_ARGS=("$@")

_resolve_codex_config_root() {
  if [ -n "${GSD_CODEX_CONFIG_ROOT:-}" ]; then
    echo "$GSD_CODEX_CONFIG_ROOT"
    return 0
  fi

  # A consumer can have unrelated project-local Codex agents. Select that
  # root only when it actually owns GSD agent TOMLs; otherwise materialize the
  # global GSD install generated by `gsd-core --codex --global`.
  if [ -d "$REPO_ROOT/.codex/agents" ] \
     && find "$REPO_ROOT/.codex/agents" -maxdepth 1 -type f -name 'gsd-*.toml' -print -quit 2>/dev/null \
        | grep -q .; then
    echo "$REPO_ROOT/.codex"
  else
    echo "${CODEX_HOME:-$HOME/.codex}"
  fi
}

_gsd_model_for_kind() {
  local kind="$1" model
  if [ "$kind" = "codex" ]; then
    model="$(codex_equiv_model "$LEAD_TIER")" || model="$LEAD_TIER"
    echo "$model"
    return 0
  fi

  if model="$(claude_equiv_model "$LEAD_TIER")"; then
    echo "$model"
    return 0
  fi
  case "$LEAD_TIER" in
    sonnet|claude-sonnet-*) echo "claude-sonnet-5" ;;
    opus|claude-opus-*) echo "claude-opus-4-8" ;;
    fable|claude-fable-*) echo "claude-fable-5" ;;
    haiku|claude-haiku-*) echo "claude-haiku-4-5-20251001" ;;
    *) echo "$LEAD_TIER" ;;
  esac
}

_gsd_effort_for_kind() {
  local kind="$1" effort
  if [ "$kind" != "codex" ]; then
    echo ""
    return 0
  fi
  effort="$(codex_equiv_effort "$LEAD_TIER")" || effort="${GSD_LEAD_EFFORT:-high}"
  echo "${GSD_LEAD_EFFORT:-$effort}"
}

_gsd_preflight_kind() {
  local kind="$1" model effort prompt
  model="$(_gsd_model_for_kind "$kind")" || return 1
  effort="$(_gsd_effort_for_kind "$kind")" || return 1
  prompt="Reply exactly FFS-GSD-PREFLIGHT-OK. This is a read-only model availability probe. Do not inspect files or use tools."

  if [ "$kind" = "codex" ]; then
    ADVERSARY_BIN_CODEX="${CODEX_BIN:-codex}" \
      _adversary_invoke_once codex "${GSD_PREFLIGHT_TIMEOUT:-60}" \
        "$model" "$effort" "$prompt"
  else
    ADVERSARY_BIN_CLAUDE="${CLAUDE_BIN:-claude}" \
      _adversary_invoke_once claude "${GSD_PREFLIGHT_TIMEOUT:-60}" \
        "$model" "$effort" "$prompt"
  fi
}

_gsd_preflight_acknowledged() {
  local output_file="$1"
  LC_ALL=C grep -Fxq 'FFS-GSD-PREFLIGHT-OK' "$output_file"
}

_run_gsd_kind() {
  local kind="$1" first rest command model effort config_root bin
  first="${COMMAND_ARGS[0]}"
  rest="${COMMAND_ARGS[*]:1}"

  if [ "$kind" = "codex" ]; then
    bin="${CODEX_BIN:-codex}"
    if ! command -v "$bin" >/dev/null 2>&1; then
      echo "gsd-run: Codex CLI not found ($bin)" >&2
      return 127
    fi
    model="$(_gsd_model_for_kind codex)" || return 1
    effort="$(_gsd_effort_for_kind codex)" || return 1

    config_root="$(_resolve_codex_config_root)"
    if [ -x "$SCRIPT_DIR/codex-model-sync.sh" ]; then
      "$SCRIPT_DIR/codex-model-sync.sh" "$config_root" >&2 || {
        echo "gsd-run: Codex model materialization failed" >&2
        return 1
      }
    fi

    case "$first" in
      /gsd-*) command="\$${first#/}" ;;
      \$gsd-*) command="$first" ;;
      *) echo "gsd-run: unsupported Codex GSD command: $first" >&2; return 2 ;;
    esac
    [ -z "$rest" ] || command="$command $rest"
    run_bounded "$TIMEOUT_SECS" "$bin" exec \
      -c "model=\"$model\"" \
      -c "model_reasoning_effort=\"$effort\"" \
      --dangerously-bypass-approvals-and-sandbox \
      "$command" </dev/null
    return $?
  fi

  bin="${CLAUDE_BIN:-claude}"
  if ! command -v "$bin" >/dev/null 2>&1; then
    echo "gsd-run: Claude CLI not found ($bin)" >&2
    return 127
  fi
  model="$(_gsd_model_for_kind claude)" || return 1
  case "$first" in
    \$gsd-*) command="/${first#\$}" ;;
    /gsd-*) command="$first" ;;
    *) echo "gsd-run: unsupported Claude GSD command: $first" >&2; return 2 ;;
  esac
  [ -z "$rest" ] || command="$command $rest"
  run_bounded "$TIMEOUT_SECS" env -u ANTHROPIC_API_KEY -u ANTHROPIC_AUTH_TOKEN \
    "$bin" --strict-mcp-config --mcp-config '{"mcpServers":{}}' \
    --dangerously-skip-permissions --model "$model" -p "$command" </dev/null
}

# Select the execution vendor using bounded, read-only model probes. Once the
# mutating GSD invocation starts it is NEVER replayed on another vendor: any
# non-zero exit may follow partial local or external mutation.
PREFLIGHT_OUT="$(mktemp "${TMPDIR:-/tmp}/ffs-gsd-preflight-out.XXXXXX")" || exit 1
PREFLIGHT_ERR="$(mktemp "${TMPDIR:-/tmp}/ffs-gsd-preflight-err.XXXXXX")" || {
  rm -f "$PREFLIGHT_OUT"
  exit 1
}
RUN_ERR=""
trap 'rm -f "$PREFLIGHT_OUT" "$PREFLIGHT_ERR" "$RUN_ERR"' EXIT

SELECTED_HOST="$ACTIVE_HOST"
_gsd_preflight_kind "$ACTIVE_HOST" >"$PREFLIGHT_OUT" 2>"$PREFLIGHT_ERR"
preflight_rc=$?
if [ "$preflight_rc" -eq 0 ] && ! _gsd_preflight_acknowledged "$PREFLIGHT_OUT"; then
  echo "gsd-run: $ACTIVE_HOST model preflight returned no valid acknowledgement" >> "$PREFLIGHT_ERR"
  preflight_rc=1
fi
if [ "$preflight_rc" -ne 0 ]; then
  cat "$PREFLIGHT_OUT"
  cat "$PREFLIGHT_ERR" >&2
  cat "$PREFLIGHT_OUT" "$PREFLIGHT_ERR" >> "$LOG_FILE"

  if ! cross_vendor_fallback_enabled; then
    exit "$preflight_rc"
  fi

  SELECTED_HOST="$(alternate_vendor_kind "$ACTIVE_HOST")" || exit "$preflight_rc"
  FALLBACK_NOTE="gsd-run: native $ACTIVE_HOST model preflight failed (rc=$preflight_rc); falling back from $ACTIVE_HOST to $SELECTED_HOST before execution"
  echo "$FALLBACK_NOTE" >&2
  echo "$FALLBACK_NOTE" >> "$LOG_FILE"

  : > "$PREFLIGHT_OUT"
  : > "$PREFLIGHT_ERR"
  _gsd_preflight_kind "$SELECTED_HOST" >"$PREFLIGHT_OUT" 2>"$PREFLIGHT_ERR"
  fallback_preflight_rc=$?
  if [ "$fallback_preflight_rc" -eq 0 ] \
     && ! _gsd_preflight_acknowledged "$PREFLIGHT_OUT"; then
    echo "gsd-run: $SELECTED_HOST model preflight returned no valid acknowledgement" >> "$PREFLIGHT_ERR"
    fallback_preflight_rc=1
  fi
  if [ "$fallback_preflight_rc" -ne 0 ]; then
    cat "$PREFLIGHT_OUT"
    cat "$PREFLIGHT_ERR" >&2
    cat "$PREFLIGHT_OUT" "$PREFLIGHT_ERR" >> "$LOG_FILE"
    echo "gsd-run: both bounded model preflights failed; no mutating drive launched" >&2
    exit "$fallback_preflight_rc"
  fi
fi

RUN_ERR="$(mktemp "${TMPDIR:-/tmp}/ffs-gsd-run-err.XXXXXX")" || exit 1
_run_gsd_kind "$SELECTED_HOST" 2>"$RUN_ERR" | tee -a "$LOG_FILE"
run_rc="${PIPESTATUS[0]}"
if [ -s "$RUN_ERR" ]; then
  cat "$RUN_ERR" >&2
  cat "$RUN_ERR" >> "$LOG_FILE"
fi
if [ "$run_rc" -eq 124 ]; then
  echo "gsd-run: $SELECTED_HOST drive timed out; cross-vendor replay suppressed because execution state is ambiguous" >&2
fi
exit "$run_rc"
