#!/usr/bin/env python3
"""Construct a title with an EXACT difflib.SequenceMatcher ratio relative to
a captured real title, for spec-011 Phase 2 Wave 0 similarity-boundary tests
(tests/bats/retro-e2e.bats). See tests/bats/helpers/retro-shims.bash header
for why this can't be a static fixture: the compared title is generated by
not-yet-written production code, so exactness is derived from the SAME
stdlib algorithm at test run time rather than assumed in advance.

The construction is exact by proof, not by search-until-close: for a target
ratio num/den and captured title of length n, a candidate

    candidate = title[:k] + (GUARD * pad)

where GUARD is a character verified absent from `title`, has
difflib.SequenceMatcher(None, title, candidate).ratio() == 2k / (n + k + pad)
EXACTLY -- title[:k] is a literal prefix of title, so the whole of it forms
one matching block with nothing left over in `candidate` to spuriously match
elsewhere, and GUARD contributes zero matches by construction. Solving
2k / (n + k + pad) = num/den for integer k, pad (0 <= k <= n) and re-checking
the ratio via difflib itself (not just the algebra) is the exactness proof.

Usage: retro_similar_title.py <captured-title-file> <num> <den> <out-file>
  e.g. `retro_similar_title.py title.txt 4 5 sim08.txt` for ratio exactly 0.8
"""
import difflib
import sys


def main() -> None:
    title_path, num_s, den_s, out_path = sys.argv[1:5]
    title = open(title_path, encoding="utf-8").read()
    num, den = int(num_s), int(den_s)
    guard = "␟"  # SYMBOL FOR UNIT SEPARATOR -- not a realistic title char
    if guard in title:
        raise SystemExit("guard character unexpectedly present in captured title")
    n = len(title)
    if n < 6:
        raise SystemExit(f"captured title too short for an exact-ratio variant: {title!r}")

    denom_coeff = 2 * den - num
    if denom_coeff <= 0:
        raise SystemExit(f"ratio {num}/{den} is not constructible by this method")

    for pad in range(0, 4 * den):
        numer = num * (n + pad)
        if numer % denom_coeff != 0:
            continue
        k = numer // denom_coeff
        if 0 <= k <= n:
            candidate = title[:k] + (guard * pad)
            ratio = difflib.SequenceMatcher(None, title, candidate).ratio()
            if abs(ratio - num / den) > 1e-9:
                raise SystemExit(f"internal proof failed: got {ratio}, wanted {num / den}")
            open(out_path, "w", encoding="utf-8").write(candidate)
            return
    raise SystemExit(f"no integer (k, pad) solution found for ratio {num}/{den} at n={n}")


if __name__ == "__main__":
    main()
