# Shared harness for spec-011 Phase 2 Wave 0 independent acceptance tests
# (tests/bats/retro.bats consent/filing additions, retro-e2e.bats,
# retro-seam.bats). bats shares no functions across files, so each suite
# `load`s this file (see tests/bats/helpers/socratic-fixtures.bash for the
# existing precedent this mirrors).
#
# Authored directly from .planning/phases/02-filing-consent-seams/*.md,
# .planning/REQUIREMENTS.md, and specs/011-retro-loop/spec.md WITHOUT
# reading lib/retro_state.py (absent) or the internals of
# scripts/gsd/retro.sh / lib/retro_scrub.py beyond black-box execution.
#
# Resolved ambiguities (contract silent on the specifics; simplest reading
# chosen per the Wave 0 brief):
#  - retro_state.py's consent/ledger/lock paths are documented only as
#    fixed paths "derived only from HOME" (02-01-PLAN interfaces), with no
#    override. Phase 1's retro.bats never isolates $HOME (only --state-root),
#    so it is unclear whether retro.sh's existing --state-root flag ALSO
#    redirects the new consent/filing state. retro_isolate_home() isolates
#    BOTH $HOME and a matching --state-root value that resolve to the exact
#    same directory ($HOME/.cache/feature-fix-swarm) -- whichever lever
#    production actually honors, tests stay hermetic and a real developer
#    $HOME is never touched.
#  - consent.json's "version" field is documented only as a "normalized
#    consent-major string" with no concrete value. Fixtures fix it as "1"
#    (current major) / "0" (stale major) as part of this acceptance
#    contract; production must adopt this scheme.
#  - the fingerprint `--search` fallback's exact flag/subcommand shape is
#    unspecified. The gh shim recognizes any `issue list` invocation whose
#    argv contains a literal `--search` token and serves a distinct canned
#    response for it.
#  - title-similarity fixtures cannot be authored statically: the title
#    string is generated by not-yet-written production code. Similarity
#    tests capture a REAL generated title from a live create call, then
#    construct exact/just-below RETRO_TITLE_SIM=0.8 variants at test run
#    time using the same stdlib difflib.SequenceMatcher algorithm the
#    interfaces section requires production to use, so exactness never
#    depends on knowing the title format in advance.

# retro_isolate_home <bats-tmpdir> <label>
retro_isolate_home() {
  local tmp="$1" label="$2"
  RETRO_HOME="$tmp/home-$label"
  mkdir -p "$RETRO_HOME"
  export HOME="$RETRO_HOME"
  RETRO_STATE="$RETRO_HOME/.cache/feature-fix-swarm"
}

# retro_seed_consent <fixture-json-path>
retro_seed_consent() {
  local fixture="$1"
  mkdir -p "$RETRO_STATE"
  chmod 700 "$RETRO_STATE"
  cp "$fixture" "$RETRO_STATE/consent.json"
  chmod 600 "$RETRO_STATE/consent.json"
}

# build_gh_shim <mock_bin_dir>
#
# Installs a scriptable `gh` PATH shim. Every invocation's argv (space
# joined) is appended to $GH_CALL_LOG. Behavior is entirely env-driven so
# each test controls upstream state without editing the shim:
#   GH_AUTH_FAIL        - set (any value) -> `gh auth status` exits 1
#   GH_LIST_FIXTURE      - JSON path served for a bounded `issue list` call
#                          (argv WITHOUT --search)
#   GH_SEARCH_FIXTURE    - JSON path served for the fingerprint search
#                          fallback (argv WITH --search); falls back to
#                          GH_LIST_FIXTURE when unset
#   GH_WRITE_FAIL_CODE   - set -> create/comment exits 1; stderr carries a
#                          marker string a test can assert never reaches
#                          the ledger/output verbatim
#   GH_NEXT_ISSUE_FILE   - counter file auto-incrementing issue numbers
#                          `issue create` returns
#   GH_CREATE_LOG        - dir; each create call's --body-file contents and
#                          --title value copied to create-<n>.body/.title
#   GH_COMMENT_LOG       - dir; each comment call's --body-file contents
#                          copied to comment-<n>.body
#   GH_COMMENT_COUNT_FILE - counter file numbering comment-<n>.body writes
#   GH_TIMING_LOG        - every create/comment call appends a
#                          sub-second-precision wall timestamp here (via
#                          python3, since BSD/macOS `date` has no %N), for
#                          pacing assertions
#
# Guard-chain form only (if/elif over argv shape) -- no bare `exit 0`
# literal anywhere: this repo's tamper scan (lib/gates.py EXIT0_PAT)
# hard-fails that even inside a heredoc-authored stub, so every branch
# either falls off the end (implicit 0) or uses a non-zero `exit N`.
build_gh_shim() {
  local mock_bin="$1"
  cat > "$mock_bin/gh" <<'SHIM'
#!/usr/bin/env bash
set -uo pipefail
printf '%s\n' "$*" >> "$GH_CALL_LOG"

has_flag() { # has_flag <needle> "$@"
  local needle="$1"; shift
  for a in "$@"; do [ "$a" = "$needle" ] && return 0; done
  return 1
}

body_file_of() { # body_file_of "$@" -> prints the value after --body-file
  local prev=""
  for a in "$@"; do
    if [ "$prev" = "--body-file" ]; then printf '%s' "$a"; return 0; fi
    prev="$a"
  done
}

next_counter() { # next_counter <counter-file> -> prints N, writes N+1
  local f="$1" n=1
  [ -n "$f" ] && [ -f "$f" ] && n="$(cat "$f")"
  [ -n "$f" ] && echo $((n + 1)) > "$f"
  printf '%s' "$n"
}

if [ "${1:-}" = "auth" ] && [ "${2:-}" = "status" ]; then
  if [ -n "${GH_AUTH_FAIL:-}" ]; then
    echo "AUTH-FAIL-MARKER: not logged in" >&2
    exit 1
  fi
  true
elif [ "${1:-}" = "issue" ] && [ "${2:-}" = "list" ]; then
  if has_flag "--search" "$@" && [ -n "${GH_SEARCH_FIXTURE:-}" ]; then
    cat "$GH_SEARCH_FIXTURE"
  elif [ -n "${GH_LIST_FIXTURE:-}" ]; then
    cat "$GH_LIST_FIXTURE"
  else
    printf '[]'
  fi
elif [ "${1:-}" = "issue" ] && [ "${2:-}" = "create" ]; then
  if [ -n "${GH_WRITE_FAIL_CODE:-}" ]; then
    echo "WRITE-FAIL-MARKER ${GH_WRITE_FAIL_CODE}: create rejected" >&2
    exit 1
  fi
  n="$(next_counter "${GH_NEXT_ISSUE_FILE:-}")"
  if [ -n "${GH_CREATE_LOG:-}" ]; then
    mkdir -p "$GH_CREATE_LOG"
    bf="$(body_file_of "$@")"
    [ -n "$bf" ] && [ -f "$bf" ] && cp "$bf" "$GH_CREATE_LOG/create-$n.body"
    prev=""
    for a in "$@"; do
      if [ "$prev" = "--title" ]; then printf '%s' "$a" > "$GH_CREATE_LOG/create-$n.title"; fi
      prev="$a"
    done
  fi
  if [ -n "${GH_TIMING_LOG:-}" ]; then python3 -c 'import time; print(time.time())' >> "$GH_TIMING_LOG"; fi
  echo "https://github.com/austinmao/feature-fix-swarm/issues/$n"
elif [ "${1:-}" = "issue" ] && [ "${2:-}" = "comment" ]; then
  if [ -n "${GH_WRITE_FAIL_CODE:-}" ]; then
    echo "WRITE-FAIL-MARKER ${GH_WRITE_FAIL_CODE}: comment rejected" >&2
    exit 1
  fi
  if [ -n "${GH_COMMENT_LOG:-}" ]; then
    mkdir -p "$GH_COMMENT_LOG"
    cn="$(next_counter "${GH_COMMENT_COUNT_FILE:-}")"
    bf="$(body_file_of "$@")"
    [ -n "$bf" ] && [ -f "$bf" ] && cp "$bf" "$GH_COMMENT_LOG/comment-$cn.body"
  fi
  if [ -n "${GH_TIMING_LOG:-}" ]; then python3 -c 'import time; print(time.time())' >> "$GH_TIMING_LOG"; fi
  true
else
  exit 64
fi
SHIM
  chmod +x "$mock_bin/gh"
}

# log_has_token <log-file> <token>
#   True iff <token> appears as a whitespace-delimited argv token in any
#   line of <log-file> -- safe against the token landing at end-of-line
#   (no trailing space to match), unlike a plain `grep ' TOKEN '`.
log_has_token() {
  grep -qE "(^| )$2( |\$)" "$1"
}

# gh_pacing_ok <timing-log> <min-seconds>
#   Prints "ok" iff every consecutive pair of timestamps in the log is at
#   least <min-seconds> apart; otherwise prints "bad: <delta>".
gh_pacing_ok() {
  python3 - "$1" "$2" <<'PY'
import sys
path, min_gap = sys.argv[1], float(sys.argv[2])
with open(path) as fh:
    ts = [float(x) for x in fh.read().split()]
ok = True
for a, b in zip(ts, ts[1:]):
    if (b - a) < min_gap:
        ok = False
        print(f"bad: {b - a}")
if ok:
    print("ok")
PY
}
